backend:
backend:
  name: github
  repo: giaoxuhongan/giaoxuhongan
  branch: main
  # 👑 ĐÃ BỔ SUNG CỔNG BẢO MẬT TRUNG GIAN NETLIFY MIỄN PHÍ
  base_url: https://netlify.com
  auth_endpoint: /auth

media_folder: "anh"
public_folder: "anh"

collections:
  - name: "loichua"
    label: "Lời Chúa Mỗi Ngày"
    folder: "loichuamoingay"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-loi-chua"
    fields:
      - { label: "Tiêu đề bài viết", name: "title", widget: "string" }
      - { label: "Ngày đăng bài", name: "date", widget: "datetime", format: "DD/MM/YYYY" }
      - { label: "Hình ảnh chủ đề", name: "image", widget: "image", required: false }
      - { label: "Câu tóm tắt Lời Chúa", name: "summary", widget: "string" }
      - { label: "Nội dung bài viết", name: "body", widget: "markdown" }


